baseURL = ""
languageCode = "en-gb"
title = "Low-carbon websites"
disableKinds = ["sitemap", "taxonomy", "taxonomyTerm"]
[params]
  cloudinaryPath  = "https://res.cloudinary.com/attractmore/image/upload/"
  cloudinaryHeroSizes = ["2800", "2000", "1600", "1300", "1120", "928", "704", "480"]
  cloudinaryHeroParms = "c_fill,f_auto,q_auto:eco,h_500,"
  
  cloudinaryFetchPath = "https://res.cloudinary.com/attractmore/image/fetch/"
  cloudinaryMainParms = "q_auto,f_auto"
  srcsetLargeWidths = ["930", "800", "640", "500", "400"]
  srcsetLargeSizes = "(max-width:45em) 90vw, 50em"
  srcsetSmallWidths = ["500", "320"]
  srcsetSmallSizes = "(max-width:30em) 40vw, 96vw"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 20
  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"
    weight = 30
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 60

[[redirects]]
  from = "/optim/blog/:image"
  to = "https://res.cloudinary.com/attractmore/image/fetch/q_auto,f_auto/https://www.attractmore.uk/images/blog/:image"
  status = 200
[[redirects]]
  from = "/optim/work/:image"
  to = "https://res.cloudinary.com/attractmore/image/fetch/q_auto,f_auto/https://www.attractmore.uk/images/work/:image"
  status = 200
[[redirects]]
  from = "/optim/services/:image"
  to = "https://res.cloudinary.com/attractmore/image/fetch/q_auto,f_auto/https://www.attractmore.uk/images/services/:image"
  status = 200
[[redirects]]
  from = "/optim/testimonials/:image"
  to = "https://res.cloudinary.com/attractmore/image/fetch/q_auto,f_auto/https://www.attractmore.uk/images/testimonials/:image"
  status = 200
[[redirects]]
  from = "/optim/misc/:image"
  to = "https://res.cloudinary.com/attractmore/image/fetch/q_auto,f_auto/https://www.attractmore.uk/images/misc/:image"
  status = 200
[[redirects]]    
  from = '/**'
  status = 404
  to = '/404.html'

