baseURL = ""
languageCode = "en-gb"
title = "Low carbon websites"
disableKinds = ["sitemap"]
paginate = 5
copyright = "© 2023 AttractMore Ltd."
[outputs]
  home = ["HTML", "RSS"]
  section = ["html", "rss"]
  taxonomy = ["html", "rss"]
  term = ["html", "rss"]

[params]
  rssTitle = "Low-carbon-websites"
  cloudinaryPath              = "https://res.cloudinary.com/attractmore/image/upload/"
  cloudinaryHeroWidths        = ["2800", "2000", "1600", "1300", "1120", "928", "704", "480"]
  cloudinaryHeroParms         = "c_fill,f_auto,q_auto:eco,h_500,"

  cloudinaryWorkMainWidths    = ["700", "600", "450", "350"]
  cloudinaryWorkMainParms     = "c_scale,f_auto,q_auto,e_sharpen,"
  cloudinaryWorkMainSizes     = "(min-width:704px) 46vw, 96vw"
  cloudinaryWorkMainFolder    = "/work-main/"

  cloudinaryWorkDetailWidths = ["820", "700", "600", "410", "350", "300"]
  cloudinaryWorkDetailParms   = "c_scale,f_auto,q_auto,e_sharpen,"
  cloudinaryWorkDetailSizes   = "(max-width: 820px) 96vw, 820px"
  cloudinaryWorkDetailFolder  = "/work/"

  cloudinaryWorkDetailMobileWidths = ["500", "320"]

  cloudinaryBlogMainWidths    = ["500", "320"]
  cloudinaryBlogMainParms     = "c_scale,f_auto,q_70,"
  cloudinaryBlogMainSizes     = "(max-width: 30em) 100vw, 300px"
  cloudinaryBlogMainFolder    = "/blog/"

  cloudinaryBlogPostFullSizes = "(max-width: 58em) 96vw, (max-width: 64em) 40em, 50em"

  cloudinaryFetchPath = "https://res.cloudinary.com/attractmore/image/fetch/"
  cloudinaryMainParms = "q_auto,f_auto"
  srcsetLargeWidths = ["930", "800", "640", "500", "400"]
  srcsetLargeSizes = "(max-width:45em) 90vw, 50em"
  srcsetSmallWidths = ["500", "320"]
  srcsetSmallSizes = "(max-width:30em) 40vw, 96vw"

  [params.author]
    email = "roger@attractmore.co.uk"
    name = 'Roger Knight'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 20
  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"
    weight = 30
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 60

